[features]
resolution = true
skip-lint = false

[programs.localnet]
viridis_staking = "4Y3DWRxpDUHfkKfEqX2joWtcTbR2kyd4wNv94jY3eHLv"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "./.private/auth_4akxcPBY95B2Vw1jEkXyLQS9v5qfv3Xu5682YsZHo3oz.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"


[test.validator]
url = "https://api.mainnet-beta.solana.com" # This is the url of the cluster that accounts are cloned from (See `test.validator.clone`).


[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "dumps/metadata.so"
